SELECT * FROM shopping_analytics_db.customer_shopping;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer_shopping
group by gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer_shopping
where discount_applied = "Yes"
and purchase_amount >= (select avg(purchase_amount) from  customer_shopping);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as Average_Product_Rating
from customer_shopping
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
round(avg(purchase_amount),2)
from customer_shopping
where shipping_type in ("Standard","Express")
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as Total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue, avg_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(sum(case when discount_applied = "Yes" then 1 else 0 end )/count(*) * 100,2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show their subscription status.
with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Return"
else "Loyal"
end as customer_segment
from customer_shopping
)

select customer_segment,count(*) as Number_of_Customer
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with items_count as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category,item_purchased)
 select item_rank,category,item_purchased, total_orders
 from items_count
 where item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyer
from customer_shopping
where previous_purchases > 5
group by subscription_status;

-- Q10. what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping
group by age_group
order by total_revenue desc;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'MyNewPassword123!';
FLUSH PRIVILEGES;